import Head from "next/head";
import Feed from "@/components/Feed";
import { useEffect, useState } from "react";
import { PostType } from "@/types/types";
import PostListItemSkeleton from "@/components/PostListItemSkeleton";

export default function Home() {
  const [postsFeed, setPostsFeed] = useState<PostType[]>();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    fetch('http://localhost:3000/api/post')
      .then(data => data.json())
      .then(posts => {
         setPostsFeed(posts.data);
         setLoading(false);
        })
      .catch(err => {
        console.log(err);
        setLoading(false);
      })
  }, [])

  const renderFeed = () => {
    if (loading) {
      return <>
        {[1,2].map((_) => <PostListItemSkeleton />)}
      </>
    } else {
      return <Feed items={postsFeed} />;
    }
  }

  return (
    <>
      <Head>
        <title>Social App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {renderFeed()}
      </>
    </>
  );
}
